#!/usr/bin/env bash
# devcontainer.sh — .devcontainer.json parsing and compose override generation.
#
# Reads .agent/devcontainer.json from the project directory and:
#   1. Computes a unique compose project name from the project path.
#   2. Generates a compose override file for image/build/mounts/env.
#   3. Exports COMPOSE_PROJECT and COMPOSE_OVERRIDE_FILE for container.sh.

set -euo pipefail

# ── path helpers ─────────────────────────────────────────────────────────

_devcontainer_config() {
    echo "$PROJECT_DIR/.agent/devcontainer.json"
}

_override_file() {
    echo "$PROJECT_DIR/.agent/container/compose.override.yml"
}

# Compute a unique project name from the project path (8-char hash prefix).
_project_name() {
    local hash
    if command -v sha256sum &>/dev/null; then
        hash=$(echo "$PROJECT_DIR" | sha256sum | head -c 8)
    elif command -v shasum &>/dev/null; then
        hash=$(echo "$PROJECT_DIR" | shasum -a 256 | head -c 8)
    else
        # Fallback: basename only
        hash=$(basename "$PROJECT_DIR" | tr -cd 'a-zA-Z0-9-_')
    fi
    echo "agentbox-${hash}"
}

# ── compose override generation ──────────────────────────────────────────

_generate_override() {
    local config
    config="$(_devcontainer_config)"

    if [ ! -f "$config" ]; then
        # No config: generate minimal override (just project mount)
        _write_minimal_override
        return
    fi

    if ! command -v jq &>/dev/null; then
        echo "[agentbox] WARNING: jq not found. Install with: brew install jq" >&2
        echo "[agentbox] Proceeding without devcontainer.json features." >&2
        _write_minimal_override
        return
    fi

    mkdir -p "$(dirname "$(_override_file)")"

    # Build the compose override YAML
    {
        echo "# Auto-generated by agentbox — do not edit manually."
        echo "# Source: $config"
        echo "services:"
        echo "  agent:"

        # --- build section ---
        local dockerfile image_name
        dockerfile=$(jq -r '.build.dockerfile // empty' "$config" 2>/dev/null || true)
        image_name=$(jq -r '.image // empty' "$config" 2>/dev/null || true)

        if [ -n "$dockerfile" ]; then
            echo "    build:"
            echo "      context: ${PROJECT_DIR}"
            echo "      dockerfile: ${dockerfile}"
        elif [ -n "$image_name" ]; then
            echo "    image: ${image_name}"
        fi

        # --- environment ---
        local env_count
        env_count=$(jq -r '.containerEnv | length // 0' "$config" 2>/dev/null || echo 0)
        if [ "$env_count" -gt 0 ]; then
            echo "    environment:"
            jq -r '.containerEnv | to_entries[] | "      \(.key): \"\(.value)\""' "$config" 2>/dev/null
        fi

        # --- volumes (mounts) ---
        local mounts_count
        mounts_count=$(jq -r '.mounts | length // 0' "$config" 2>/dev/null || echo 0)
        if [ "$mounts_count" -gt 0 ]; then
            echo "    volumes:"
            jq -r '.mounts[]' "$config" 2>/dev/null | while read -r mount; do
                echo "      - ${mount}"
            done
        fi

        # Always mount post-create script so entrypoint can pick it up
        echo "      - ${PROJECT_DIR}/.agent/container/post-create.sh:/.agentbox/post-create.sh:ro"

    } > "$(_override_file)"
}

_write_minimal_override() {
    mkdir -p "$(dirname "$(_override_file)")"
    cat > "$(_override_file)" <<EOF
# Auto-generated by agentbox — no devcontainer.json found.
services:
  agent:
EOF
    # Add post-create mount even in minimal mode
    echo "    volumes:"
    echo "      - ${PROJECT_DIR}/.agent/container/post-create.sh:/.agentbox/post-create.sh:ro" \
        >> "$(_override_file)"
}

# ── public API ───────────────────────────────────────────────────────────

# Initialize devcontainer config. Must be called before any container operations.
# Sets global variables: COMPOSE_PROJECT, COMPOSE_OVERRIDE_FILE
devcontainer_init() {
    COMPOSE_PROJECT="$(_project_name)"
    COMPOSE_OVERRIDE_FILE="$(_override_file)"
    export COMPOSE_PROJECT COMPOSE_OVERRIDE_FILE

    _generate_override

    # Read mounts for volume management
    local config
    config="$(_devcontainer_config)"
    if [ -f "$config" ] && command -v jq &>/dev/null; then
        AGENTBOX_MOUNTS=$(jq -r '.mounts // [] | join("\n")' "$config" 2>/dev/null || echo "")
        export AGENTBOX_MOUNTS
    else
        AGENTBOX_MOUNTS=""
        export AGENTBOX_MOUNTS
    fi
}
