#!/usr/bin/env bash
# devcontainer.sh — .devcontainer.json parsing and compose override generation.
#
# Reads .agent/devcontainer.json from the project directory and:
#   1. Computes a unique compose project name from the project path.
#   2. Generates a compose override file for image/build/mounts/env.
#   3. Exports COMPOSE_PROJECT and COMPOSE_OVERRIDE_FILE for container.sh.

set -euo pipefail

# ── path helpers ─────────────────────────────────────────────────────────

_devcontainer_config() {
    echo "$PROJECT_DIR/.agent/devcontainer.json"
}

_override_file() {
    echo "$PROJECT_DIR/.agent/container/compose.override.yml"
}

# Compute a unique project name from the project path (8-char hash prefix).
_project_name() {
    local hash
    if command -v sha256sum &>/dev/null; then
        hash=$(echo "$PROJECT_DIR" | sha256sum | head -c 8)
    elif command -v shasum &>/dev/null; then
        hash=$(echo "$PROJECT_DIR" | shasum -a 256 | head -c 8)
    else
        # Fallback: basename only
        hash=$(basename "$PROJECT_DIR" | tr -cd 'a-zA-Z0-9-_')
    fi
    echo "agentbox-${hash}"
}

# Convert devcontainer mount format ("source=X,target=Y,type=volume") to
# docker compose volume syntax ("X:Y" for volumes, "/X:Y" for binds).
_convert_mount() {
    local mount="$1"
    local source target type
    source=$(echo "$mount" | sed -n 's/.*source=\([^,]*\).*/\1/p')
    target=$(echo "$mount" | sed -n 's/.*target=\([^,]*\).*/\1/p')
    type=$(echo "$mount" | sed -n 's/.*type=\([^,]*\).*/\1/p')
    if [ -z "$source" ] || [ -z "$target" ]; then
        echo "$mount"
        return
    fi
    echo "${source}:${target}"
}

# ── compose override generation ──────────────────────────────────────────

_generate_override() {
    local config
    config="$(_devcontainer_config)"

    if [ ! -f "$config" ]; then
        # No config: generate minimal override (just project mount)
        _write_minimal_override
        return
    fi

    if ! command -v jq &>/dev/null; then
        echo "[agentbox] WARNING: jq not found. Install with: brew install jq" >&2
        echo "[agentbox] Proceeding without devcontainer.json features." >&2
        _write_minimal_override
        return
    fi

    mkdir -p "$(dirname "$(_override_file)")"

    # Build the compose override YAML
    {
        echo "# Auto-generated by agentbox — do not edit manually."
        echo "# Source: $config"
        echo "services:"
        echo "  agent:"

        # --- build section ---
        local dockerfile image_name
        dockerfile=$(jq -r '.build.dockerfile // empty' "$config" 2>/dev/null || true)
        image_name=$(jq -r '.image // empty' "$config" 2>/dev/null || true)

        if [ -n "$dockerfile" ]; then
            echo "    build:"
            echo "      context: ${PROJECT_DIR}"
            echo "      dockerfile: ${dockerfile}"
        elif [ -n "$image_name" ]; then
            echo "    image: ${image_name}"
        fi

        # --- environment ---
        local env_count
        env_count=$(jq -r '.containerEnv | length // 0' "$config" 2>/dev/null || echo 0)
        if [ "$env_count" -gt 0 ]; then
            echo "    environment:"
            jq -r '.containerEnv | to_entries[] | "      \(.key): \"\(.value)\""' "$config" 2>/dev/null
        fi

        # --- volumes (mounts) ---
        local mounts_count has_postcreate
        mounts_count=$(jq -r '.mounts | length // 0' "$config" 2>/dev/null || echo 0)
        has_postcreate=$(jq -r '.postCreateCommand // empty' "$config" 2>/dev/null || true)

        if [ "$mounts_count" -gt 0 ]; then
            echo "    volumes:"
            jq -r '.mounts[]' "$config" 2>/dev/null | while read -r mount; do
                echo "      - $(_convert_mount "$mount")"
            done
        fi

        # Mount post-create script so entrypoint can pick it up on first start.
        if [ -n "$has_postcreate" ]; then
            if [ "$mounts_count" -eq 0 ]; then
                echo "    volumes:"
            fi
            echo "      - ${PROJECT_DIR}/.agent/container/post-create.sh:/.agentbox/post-create.sh:ro"
        fi

    } > "$(_override_file)"

    # Append top-level volumes: declaration for named volumes referenced in mounts.
    # These are pre-created by volume_create_all() so we declare them external
    # to avoid compose prefixing their names.
    local volumes_block
    volumes_block=$(jq -r '.mounts // [] | .[]' "$config" 2>/dev/null | while read -r mount; do
        local type
        type=$(echo "$mount" | sed -n 's/.*type=\([^,]*\).*/\1/p')
        if [ "$type" = "volume" ]; then
            local vol_name
            vol_name=$(echo "$mount" | sed -n 's/.*source=\([^,]*\).*/\1/p')
            [ -n "$vol_name" ] && echo "  ${vol_name}:"
            [ -n "$vol_name" ] && echo "    external: true"
        fi
    done)
    if [ -n "$volumes_block" ]; then
        {
            echo "volumes:"
            echo "$volumes_block"
        } >> "$(_override_file)"
    fi
}

_write_minimal_override() {
    mkdir -p "$(dirname "$(_override_file)")"
    cat > "$(_override_file)" <<EOF
# Auto-generated by agentbox — no devcontainer.json found.
services:
  agent:
EOF
}

# ── public API ───────────────────────────────────────────────────────────

# Initialize devcontainer config. Must be called before any container operations.
# Sets global variables: COMPOSE_PROJECT, COMPOSE_OVERRIDE_FILE
devcontainer_init() {
    COMPOSE_PROJECT="$(_project_name)"
    COMPOSE_OVERRIDE_FILE="$(_override_file)"
    export COMPOSE_PROJECT COMPOSE_OVERRIDE_FILE

    _generate_override

    # Read mounts for volume management
    local config
    config="$(_devcontainer_config)"
    if [ -f "$config" ] && command -v jq &>/dev/null; then
        AGENTBOX_MOUNTS=$(jq -r '.mounts // [] | join("\n")' "$config" 2>/dev/null || echo "")
        export AGENTBOX_MOUNTS
    else
        AGENTBOX_MOUNTS=""
        export AGENTBOX_MOUNTS
    fi
}
